[package]
name = "notesy_core"
version = "0.1.0"
authors = ["Sophie <sophie.d21401@gmail.com>"]
edition = "2018"

[lib]
name = "notesy_core"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
